import numpy as np
onearray=np.array([10, 15, 20, 25, 30, 35, 40, 45])
print(onearray[0])
print(onearray[-1])
print(onearray[2])
print(onearray.shape)
print(onearray[0:3])
print(onearray[::2])
reshapearray=onearray.reshape(2,4)
print(reshapearray)
print(onearray.reshape(2,4))
fourarray=np.array([50,55,60,65])
longerarray=np.concatenate((fourarray,onearray))
print(longerarray)
splitarray=np.split(longerarray,3)
print(splitarray)
splitarra=np.split(longerarray,5)
print(splitarra)
